import { NavBar } from "./auth/NavBar";
import "./globals.css";
import { Roboto } from "next/font/google";
import { ServerThemeProvider } from "next-themes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ServerThemeProvider attribute="class">
      <html lang="en">
        <body className={`mx-4 md:mx-48 xl:mx-96 ${roboto.variable}`}>
          {/* @ts-expect-error Async Server Component */}
          <NavBar />
          {children}
        </body>
      </html>
    </ServerThemeProvider>
  );
}
